[build]
	functions = "functions"
	[build.environment]
		NETLIFY_NEXT_PLUGIN_SKIP = "true"
		NODE_VERSION = "14"


[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200

[functions]
    node_bundler = "esbuild"
